### ISSUE TITLE
Support version files in custom locations

### ISSUE THREAD

**Issue by MrAlias** [open-telemetry/opentelemetry-go-build-tools#994]
When running `multimod prerelease` there are times I need it to update a `version.go` file that contains the module version that is not located in the root of the directory.

I would like to be able to specify a custom location of this file in the `versions.yaml` module set definition and have the tooling update the version.

**Comment by MrAlias** [comment]
I plan to add a new `modules` section to the configuration. For example:

```yaml
module-sets:
  mod-set-1:
    version: v0.0.1
    modules:
      - go.opentelemetry.io/test/test1
      - go.opentelemetry.io/test/test2
  mod-set-2:
    version: v0.1.0
    modules:
      - go.opentelemetry.io/test3
excluded-modules:
  - go.opentelemetry.io/excluded1
modules:
  go.opentelemetry.io/test/test1:
    version-refs:
      - ./versions.go
      - ./internal/version/versions.go
  go.opentelemetry.io/test/test2:
    version-refs:
      - ./internal/deeper/version/versions.go
  go.opentelemetry.io/excluded1:
    version-refs:
      - ./sub/pkg/version/versions.go
  go.opentelemetry.io/unknown:
    version-refs:
      - ../unknown/versions.go
```

Alternatively, the following was considered:

```yaml
module-sets:
  mod-set-1:
    version: v0.0.1
    modules:
      - go.opentelemetry.io/test/test1:
          version-refs:
            - ./versions.go
            - ./internal/version/versions.go
      - go.opentelemetry.io/test/test2:
          version-refs:
            - ./internal/deeper/version/versions.go
  mod-set-2:
    version: v0.1.0
    modules:
      - go.opentelemetry.io/test3
excluded-modules:
  - go.opentelemetry.io/excluded1
```

This allows custom overrides of a module per module set. However:

- An override per module set is not expected to be a useful feature
- Custom hooks need to be added to parse the config given the modules definition will be a "one of" type
- Custom hooks need to be added to ensure that each module list entry only contains one map entry

Both approaches are backward-compatible. However, the first approach seems cleaner from an implementation and use perspective.
